### ISSUE TITLE
Simple Slavery Compatibility

### ISSUE THREAD

**Issue by Aviuz** [Aviuz/PrisonLabor#137] opened 2019-01-26 18:06 UTC
>Install both Prison Labor 0.10.0 dev and Simple Slavery latest version.
Enslaving prisoner (Simple Slavery mechanics) will result in the pawn recruited, but without the usual notification of successful enslavement and the pawn is now a colonist instead of a slave.
Both mod works fine using Prison Labor 0.9.11 and older versions.
So, I guess it;s the 0.10.0 dev version.

**Comment by MarkSill** [comment] 2020-07-01 20:19
I'm the current maintainer of the [1.1 version](https://github.com/MarkSill/Simple-Slavery). I just fixed this bug on my end, but it seems like it's caused by Prison Labor [setting a pawn's `workSettings` field to null](https://github.com/Aviuz/PrisonLabor/blob/7fde62914d93c3d9002597b1cc565955b28303b4/Source/HarmonyPatches/Patches_WorkSettings/Patch_ResetWorktableWhenRecruited.cs#L22).

Being new to RimWorld modding, I don't know if I'm handling this correctly, but here's I think it could be fixed on Prison Labor's end:

```c#
// Instead of __instance.workSettings = null;
__instance.workSettings = new Pawn_WorkSettings(__instance);
__instance.workSettings.EnableAndInitialize();
```

**Comment by Hazzer** [comment] 2020-07-01 20:27
Looking on decompiled method SetFaction method just : `__instance.workSettings = new Pawn_WorkSettings(__instance); ` should be enought

**Comment by MarkSill** [comment] 2020-07-01 20:32
Pawn.SetFaction calls `this.workSettings.EnableAndInitialize()` if joining the player faction and `workSettings` isn't null.

**Comment by Hazzer** [comment] 2020-07-01 22:43
Done. it will be in next patch :)

**Closed** 2020-07-01 22:43 UTC
